// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfhhj-tVHh5Yf-i_AAaCYwBoEAafZqc8',
    appId: '1:214531913930:web:4d5a6ee409e54a6cf01c33',
    messagingSenderId: '214531913930',
    projectId: 'doctor-hunt-dev',
    authDomain: 'doctor-hunt-dev.firebaseapp.com',
    storageBucket: 'doctor-hunt-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Pqcc9ebGtRshhkNShYTO8vClM71fKwc',
    appId: '1:214531913930:android:753beea9f881944ff01c33',
    messagingSenderId: '214531913930',
    projectId: 'doctor-hunt-dev',
    storageBucket: 'doctor-hunt-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLm8jiKJ80EST0WOEnT-42No9R6_8EXBw',
    appId: '1:214531913930:ios:f24ccee4d17ce431f01c33',
    messagingSenderId: '214531913930',
    projectId: 'doctor-hunt-dev',
    storageBucket: 'doctor-hunt-dev.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLm8jiKJ80EST0WOEnT-42No9R6_8EXBw',
    appId: '1:214531913930:ios:f24ccee4d17ce431f01c33',
    messagingSenderId: '214531913930',
    projectId: 'doctor-hunt-dev',
    storageBucket: 'doctor-hunt-dev.firebasestorage.app',
    iosBundleId: 'com.example.doctorHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWfhhj-tVHh5Yf-i_AAaCYwBoEAafZqc8',
    appId: '1:214531913930:web:137ded03b46db5aef01c33',
    messagingSenderId: '214531913930',
    projectId: 'doctor-hunt-dev',
    authDomain: 'doctor-hunt-dev.firebaseapp.com',
    storageBucket: 'doctor-hunt-dev.firebasestorage.app',
  );
}
